#solapi:
#  api-key: NCS4V4HHHBMCEQ94
#  api-secret: "BJ247KPS2TLVIWZWLMCBTHBX6HPONR48"
#  from-number: "01073672151"
#
#app:
#  mail:
#    from-address: "chanho8629@gmail.com"
#
#spring:
#  mail:
#    username: "chanho8629@gmail.com"
#    password: "hdzniyhrjhjvoiax"
